Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/experiment.py", line 96, in <module>
    training_experiment_1.run()
  File "src/experiment.py", line 66, in run
    train_agent(instances=self.training_contexts, pathToAgents=self.results_path, agent_params=self.agent_params, agent=self.agent,
  File "/home/marco/Desktop/Learning-Synthesis/src/train.py", line 48, in train_agent
    agent.train(env[instances[0]], seconds=seconds, max_steps=total_steps, copy_freq=copy_freq,
  File "/home/marco/Desktop/Learning-Synthesis/src/agent.py", line 83, in train
    obs2, reward, done, info = env.step(a)
  File "/home/marco/Desktop/Learning-Synthesis/src/environment.py", line 54, in step
    self.javaEnv.expandAction(action)
